### ISSUE TITLE
 Exploring openFMB

### ISSUE THREAD

**Issue by h-abinaya28** [gec/openfmb-dds-adapters#2]
Hi
I am new to github as well as the openFMB concept. I have been reading a while about it and found a github repository***\* gec/openfmb-dds-adapters and openfmb-sgip****. I got the maven project compiled on eclipse successfully (in my windows 7 64 bit). But the issue is,what should be done with this code is a puzzle for me.
I want to make two devices interoperable using openfmb. Is there any example and full detail about how to proceed with it? Sorry , i am an amateur trying to learn this and experiment . Any document related to the usage of this code correctly on devices to make them interoperable will be appreciated.

**Comment by devans** [comment]
OpenFMB has been used to define a data model for common microgrid resources. You can find that model in IDL form, the specification for DDS data types, in this repository. The adapters themselves are used to translate DNP3 and Modbus device data to DDS. Applications on the DDS bus then have access to this data.

**Comment by h-abinaya28** [comment]
Okay ,so If i want to understand the code written in this repository,from where should i begin exploring and understanding?

**Comment by h-abinaya28** [comment]
I am trying to import this maven project into eclipse Kepler Java EE edition ,I am facing a lot of issues in importing this. Can you please tell me the procedure with correct eclipse version and configurations so that i am able to successfully build this project?

**Comment by devans** [comment]
We don't use Eclipse and don't have a procedure as such for importing.

**Comment by h-abinaya28** [comment]
Then what do you use to compile the above codebase?
