### ISSUE TITLE
Running jar files.

### ISSUE THREAD

**Issue by h-abinaya28** [gec/openfmb-dds-adapters#3]
hi,
I want to know which is the starting point of this project codebase? and i am unable to run the jar file so created in Linux as it gives out an error saying "no main manifest attribute".Can you  please provide me with the correct procedure to build and run this maven project.You help is truly appreciated. Thanks in advance.  

Abinaya H
Landis gyr
GDC,India

**Comment by devans** [comment]
The readme markdown file in the root of the repository describes how to run the DNP3/Modbus processes using the -cp switch and the class name.
