### ISSUE TITLE
Modbus Library issue

### ISSUE THREAD

**Issue by h-abinaya28** [gec/openfmb-dds-adapters#4]
I had downloaded the modbus library master from the link given in openfmb README , I tried "mvn install" to create jar files in Fedora( 64-bit ). but i find some test being failed. I am attaching the log file for the reference. Please tell me the issue and its workaround. 
And After compiling the modbus library :
1. what needs to be done further? 
2. Will this modbus library run parallel to the openFmb on the same device? 
[Log_modbus_library.txt](https://github.com/gec/openfmb-dds-adapters/files/246482/Log_modbus_library.txt)

**Comment by devans** [comment]
You can comment out the test block starting at line 302 in NioTests.scala as a workaround. It's expecting a timeout and the OS is informing it there's no route instead.

The modbus library is used by the Modbus DDS adapters. To build the Modbus DDS adapters you shouldn't have to build the Modbus library itself, it should download it from the project's maven repository.
